# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."vaultwarden" = {
    image = "vaultwarden/server:latest";
    environment = {
      "ADMIN_TOKEN" = "";
      "ROCKET_TLS_CERTS" = "\"/data/certs.pem\"";
      "ROCKET_TLS_KEY" = "\"/data/key.pem\"";
      "SIGNUPS_ALLOWED" = "true";
      "WEBSOCKET_ENABLED" = "true";
    };
    volumes = [
      "/home/sven/bitwarden:/data:rw"
    ];
    ports = [
      "9445:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=vaultwarden"
      "--network=hel_default"
    ];
  };
  systemd.services."podman-vaultwarden" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-hel_default.service"
    ];
    requires = [
      "podman-network-hel_default.service"
    ];
    partOf = [
      "podman-compose-hel-root.target"
    ];
    wantedBy = [
      "podman-compose-hel-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-hel_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f hel_default";
    };
    script = ''
      podman network inspect hel_default || podman network create hel_default
    '';
    partOf = [ "podman-compose-hel-root.target" ];
    wantedBy = [ "podman-compose-hel-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-hel-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
