# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  
  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."ncdb" = {
    image = "mariadb:latest";
    environment = {
      "MYSQL_DATABASE" = "nextclouddb";
      "MYSQL_PASSWORD" = "nextcloud";
      "MYSQL_ROOT_PASSWORD" = "nextcloud";
      "MYSQL_USER" = "nextcloud";
    };
    volumes = [
      "/home/sven/media/ncconfigs/mariadb:/var/lib/mysql:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=db"
      "--network=nextcloud"
    ];
  };
  systemd.services."podman-ncdb" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-nextcloud.service"
    ];
    requires = [
      "podman-network-nextcloud.service"
    ];
    partOf = [
      "podman-compose-nextcloud-root.target"
    ];
    wantedBy = [
      "podman-compose-nextcloud-root.target"
    ];
  };
  virtualisation.oci-containers.containers."ncredis" = {
    image = "redis:7-alpine";
    cmd = [ "redis-server" "--requirepass" "nextcloud_redis_pass" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=redis"
      "--network=nextcloud"
    ];
  };
  systemd.services."podman-ncredis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-nextcloud.service"
    ];
    requires = [
      "podman-network-nextcloud.service"
    ];
    partOf = [
      "podman-compose-nextcloud-root.target"
    ];
    wantedBy = [
      "podman-compose-nextcloud-root.target"
    ];
  };
  virtualisation.oci-containers.containers."nextcloud" = {
    image = "nextcloud";
    environment = {
      "MYSQL_DATABASE" = "nextclouddb";
      "MYSQL_HOST" = "db";
      "MYSQL_PASSWORD" = "nextcloud";
      "MYSQL_USER" = "nextcloud";
      "NEXTCLOUD_ADMIN_PASSWORD" = "N-nothalium.09";
      "NEXTCLOUD_ADMIN_USER" = "ncadmin";
      "REDIS_HOST" = "redis";
      "REDIS_HOST_PASSWORD" = "nextcloud_redis_pass";
      "REDIS_PORT" = "6379";
    };
    volumes = [
      "/home/sven/media/ncconfigs/data:/var/www/html:rw"
      "/home/sven/media/ncdata/external_data1:/mnt/data_main1:rw"
      "/home/sven/media/ncdata/external_data2:/mnt/data_main2:rw"
    ];
    ports = [
      "5080:80/tcp"
    ];
    dependsOn = [
      "ncdb"
      "ncredis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=nextcloud"
      "--network=nextcloud"
    ];
  };
  systemd.services."podman-nextcloud" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-nextcloud.service"
    ];
    requires = [
      "podman-network-nextcloud.service"
    ];
    partOf = [
      "podman-compose-nextcloud-root.target"
    ];
    wantedBy = [
      "podman-compose-nextcloud-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-nextcloud" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f nextcloud";
    };
    script = ''
      podman network inspect nextcloud || podman network create nextcloud --driver=bridge
    '';
    partOf = [ "podman-compose-nextcloud-root.target" ];
    wantedBy = [ "podman-compose-nextcloud-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-nextcloud-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
