# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  

  # Containers
  virtualisation.oci-containers.containers."gitlab" = {
    image = "gitlab/gitlab-ce:latest";
    environment = {
  external_url =  "https://gitlab.thethalium.ch";
    };
    volumes = [
      "/home/sven/config:/etc/gitlab:rw"
      "/home/sven/data:/var/opt/gitlab:rw"
      "/home/sven/logs:/var/log/gitlab:rw"
    ];
    ports = [
      "4080:80/tcp"
      "4443:443/tcp"
      "422:22/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=gitlab.thethalium.ch"
      "--network-alias=gitlab"
      "--network=hello_default"
      "--shm-size=268435456"
    ];
  };
  systemd.services."podman-gitlab" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-hello_default.service"
    ];
    requires = [
      "podman-network-hello_default.service"
    ];
    partOf = [
      "podman-compose-hello-root.target"
    ];
    wantedBy = [
      "podman-compose-hello-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-hello_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f hello_default";
    };
    script = ''
      podman network inspect hello_default || podman network create hello_default
    '';
    partOf = [ "podman-compose-hello-root.target" ];
    wantedBy = [ "podman-compose-hello-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-hello-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
